spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learning?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: "admin"
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ENC(TVd8jt3OBmkbtLFhytsLKMX97SxESPiryQWviK37iDfEFMNcfhr25XMIdwvLd0iT2GrmAt1qAwc+8RfPjfrPvw==)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  liquibase:
    enabled: true
    drop-first: false
    change-log: db/changelog/changelog-master.xml
    default-schema: public
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
