spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learning?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=yes&characterEncoding=UTF-8
    username: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: "123456"
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  liquibase:
    enabled: true
    change-log: db/changelog/changelog-master.xml
    default-schema: public
gemini:
  api-key: value
google-search:
  api-key: value
  engine-id: value
