spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learning?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: "admin"
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: "password"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect