spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learning?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=yes&characterEncoding=UTF-8
    username: "admin"
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: "password"
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  liquibase:
    enabled: true
    change-log: db/changelog/changelog-master.xml
    default-schema: public
gemini:
  api-key: ENC(GZniHlKS1bYb5COjJG7ZloQuhN6BU0b6GoQcZBMnwnLtiEJcIhWeGqIZqOKjTSvM9eXZOVnlQJgW9GbCWQpadT6g6Ud3swZ3YyryYFLBXG0=)

