spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learning?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=yes&characterEncoding=UTF-8
    username: "admin"
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ENC(TVd8jt3OBmkbtLFhytsLKMX97SxESPiryQWviK37iDfEFMNcfhr25XMIdwvLd0iT2GrmAt1qAwc+8RfPjfrPvw==)
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  liquibase:
    enabled: true
    change-log: db/changelog/changelog-master.xml
    default-schema: public
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
gemini:
  api-key: ENC(JtqwKAE0dIRxPHm7HuJmQeBPurU++fn/+BaI6aVUTNXu/2dZBqGp5cGVeQ7w6GgQ0AnwXZmyWy/qnBcxuHk6ev1xMcWAf28iyI28ydxFeao=)
google-search:
  api-key: ENC(dTYS2dSPAbd9DNgvv8ba6MAIDPyLhP3Nw5h6JaWI6L/WFQ6Vh+YN8mVgj0V+gWvTKWl9QcBB1uG9TT4Pvgfhma4AB3uOfK3S4UIhD2za9z8=)
  engine-id: ENC(WoaXwwTfmj5Lay7iKjop1wBZQZ5aOcEm00QVsJgCqvwcpghRZmkRo4euMKteaRH50xkl342s17R3T33mBnz64g==)
springdoc:
  swagger-ui:
    url: https://api-ggstudy.ptit.id.vn/v3/api-docs