spring:
  application:
    name: GGStudy
  profiles:
    active: local
  security:
    oauth2:
      resourceserver:
        jwt:
          audiences: https://api-ggstudy.ptit.id.vn
          issuer-uri: https://dev-q6qkwuzccru8mu10.us.auth0.com/
logging:
  file:
    path: backend/logs
    name: app.log
  profile:
    active: local
management:
  endpoints:
    web:
      exposure:
        include: 'health'
  endpoint:
    health:
      show-details: always
springdoc:
  swagger-ui:
    url: https://api-ggstudy.ptit.id.vn/v3/api-docs