spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learning?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=yes&characterEncoding=UTF-8
    username: "admin"
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ENC(TVd8jt3OBmkbtLFhytsLKMX97SxESPiryQWviK37iDfEFMNcfhr25XMIdwvLd0iT2GrmAt1qAwc+8RfPjfrPvw==)
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  liquibase:
    enabled: true
    change-log: db/changelog/changelog-master.xml
    default-schema: public
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
gemini:
  api-key: ENC(OmSIBjOVMchVTLVEtkFcQXlD2iMFy164c6XhC1bh+nYF9OOVlnOpSLjuD56ZBz37hNGuL8Fxm/70qfSr4QGRQ5IlvE9c4G2ioh+7djO8H/Q=)

