spring:
  application:
    name: GGStudy
  profiles:
    active: local
  liquibase:
    enabled: true
    drop-first: false
    change-log: db/changelog/changelog-master.xml
    default-schema: public
logging:
  file:
    path: backend/logs
    name: app.log
management:
  endpoints:
    web:
      exposure:
        include: 'health'
  endpoint:
    health:
      show-details: always
