spring:
  application:
    name: GGStudy
  profiles:
    active: local
logging:
  file:
    path: backend/logs
    name: app.log
  profile:
    active: local
management:
  endpoints:
    web:
      exposure:
        include: 'health'
  endpoint:
    health:
      show-details: always
springdoc:
  swagger-ui:
    url: https://api-ggstudy.ptit.id.vn/v3/api-docs