name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - deploy-fe
      - test-deploy-fe
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Change directory to frontend and install dependencies
        run: |
          cd frontend
          npm install
      - name: Build project
        run: npm run build
        working-directory: ./frontend
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GGSTUDY_9A525 }}'
          channelId: live
          projectId: ggstudy-9a525
          entryPoint: frontend